import * as React from "react";

import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import Layout from "../components/layout";

import Composition from "../preprocess/composition.json";

import { useTheme } from "next-themes";
import styled from "@emotion/styled";
// import Select, { SelectChangeEvent } from '@mui/material/Select';

import { DarkModeSwitch } from "react-toggle-dark-mode";
import { css } from "@emotion/react";
import DarkmodeToggle from "../components/darkmodeToggle";

import Search from "../components/search";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hola</h1>
        <Search />
      </main>

      <DarkmodeToggle
        size={32}
        style={{
          marginLeft: "100px",
        }}
      />

      <footer>
        <p>footer</p>
      </footer>
    </Layout>
  );
};

export default Home;
